### PR TITLE
Bring back internal scribe tool

### PR DESCRIPTION
**Pull request by gkellogg**
I found that scribejs wasn't generating correct HTML, and was incompatible with the meeting index generation we use. Unfortunately, scrawl.js was quite out of date WRT the way we use IRC now, so updated it to allow for the `:+-` variations on `scribe`, `present`, `regrets`, and so forth.

While doing so, I found that scribejs wasn't properly keeping track of the in-scope scribes, so this version will only treat a line as scribed if it's surrounded by `scribe+` and `scribe-`.

Note sure if a version of scrawl.js (from @msporny I think) is used anywhere else, but some of the updates may be useful. It will continue to work with the Markdown output from scribejs, if it is present.

### CODE REVIEW

**Comment by msporny** [comment]
> Note sure if a version of scrawl.js (from @msporny I think) is used anywhere else, but some of the updates may be useful.

It's used in at least 4-5 groups in the W3C Credentials CG, and has been updated a bit over the past two or so to use features available in our Jitsi meeting software:

https://github.com/w3c-ccg/meetings/commits/main/scribe-tool/scrawl.js

We now have auto-scribe (using Google Transcriber), integration w/ Jitsi chat and IRC (via CGBot), and I think added some things like scribe+. I haven't had the time to look at these PRs, but I expect they'd be very useful to the CG... and perhaps it's time to think about pulling all this out into a common code base? We're definitely duplicating work at this point.

**Comment by gkellogg** [comment]
> > Note sure if a version of scrawl.js (from @msporny I think) is used anywhere else, but some of the updates may be useful.
> 
> It's used in at least 4-5 groups in the W3C Credentials CG, and has been updated a bit over the past two or so to use features available in our Jitsi meeting software:
> 
> https://github.com/w3c-ccg/meetings/commits/main/scribe-tool/scrawl.js

You probably have some better code structure and more comprehensive features than I've added, and I'm sure there are improvements to be taken from both code bases.

> We now have auto-scribe (using Google Transcriber), integration w/ Jitsi chat and IRC (via CGBot), and I think added some things like scribe+. I haven't had the time to look at these PRs, but I expect they'd be very useful to the CG... and perhaps it's time to think about pulling all this out into a common code base? We're definitely duplicating work at this point.

Most definitely. The C14N group may end up using this too, I suspect, and there's probably more automation and integration that can help.

**Comment by gkellogg** [comment]
@msporny: You might want to look at the `processPeople` method, which is used for all `present|chair|scribe|regrets|...[:+\-]` processing (inspired by scribejs):

https://github.com/json-ld/minutes/blob/f807713512584544d864ebefc1d8c0749c63278a/scribe-tool/scrawl.js#L67-L105.

Also, the scribe rules were updated for `scribe-` in addition to `scribe:` and `scribe+`, so that the currently active list of scribes is considered when processing a line.

**Comment by gkellogg** [comment]
@msporny I added much of what you have in the CCG version. The alias accounting, and handling of present/regrets/char/etc. has diverged and probably requires more thinking. I generally prefer what I've done, as it modularizes the data better, but it does not include as many potential aliases as your version.

**Pull request merged**
